version: '3'

services:
  memgraph:
    image: memgraph/memgraph-mage:latest
    container_name: memgraph-mage
    ports:
      - "7687:7687"
      - "7444:7444"
    command: [ "--log-level=TRACE" ]

  lab:
    image: memgraph/lab:latest
    container_name: memgraph-lab
    ports:
      - "3000:3000"
    depends_on:
      - memgraph
    environment:
      - QUICK_CONNECT_MG_HOST=memgraph
      - QUICK_CONNECT_MG_PORT=7687

  redis:
    container_name: magicscroll-redis
    image: "redis/redis-stack-server:latest"
    ports:
      - "6379:6379" # Redis Server
      - "8001:8001" # Redis Insight

volumes:
  redis_data:
  mg_lib:
  mg_log:
  mg_etc:
