[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "scramble"
version = "0.1.0"
authors = [
    { name = "Rob Spectre" }
]
description = "Semantic Compression for AI Dialogue"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "click>=8.0.0",
    "numpy>=1.20.0",
    "sentence-transformers>=2.0.0"
]

[project.scripts]
ramble = "scramble.cli.app:cli"

[tool.hatch.build.targets.wheel]
packages = ["src/scramble"]