[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "scramble"
version = "0.1.0"
authors = [{ name = "lux" }]
description = "Semantic Compression for AI Dialogue"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "rich",            # For CLI formatting
    "nltk",           # For text processing
    "anthropic",      # For Claude API
    "click",          # For CLI interface
    "sentence-transformers",  # For semantic operations
    "numpy",          # Required by sentence-transformers
    "dateparser",     # For parsing dates in context search
    "textual",        # RambleMAXX interface
    "litellm"         # LLM comms
]

[project.scripts]
ramble = "ramble.app:cli"  # Updated path for the new structure
maxx = "ramblemaxx.app:RambleMaxx.run" 

[tool.hatch.build.targets.wheel]
packages = ["scramble", "ramble", "ramblemaxx"]  # Updated to include both packages