[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "scramble"
version = "0.1.0"
authors = [{ name = "lux" }]
description = "Semantic Compression for AI Dialogue"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "rich",
    "nltk",
    "anthropic>=0.18.0",
    "click",
    "sentence-transformers",
    "click>=8.0.0",
    "numpy>=1.20.0",
    "sentence-transformers>=2.0.0",
    "datetime",
    "dateparse",
    "nltk>=3.8.2",
]

[project.scripts]
ramble = "scramble.cli.app:cli"

[tool.hatch.build.targets.wheel]
packages = ["src/scramble"]
