[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "scramble"
version = "0.1.0"
authors = [{ name = "lux" }]
description = "Semantic Compression for AI Dialogue"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
dependencies = [
    "rich",
    "nltk",
    "anthropic",
    "click",
    "sentence-transformers>=2.5.0",
    "numpy",
    "dateparser",
    "textual",
    "pyte",
    "redis>=5.0.1",
    "chromadb>=0.4.22",
    "chromadb-client>=0.6.2",
    "llama-index-core>=0.10.0",
    "llama-index-embeddings-huggingface>=0.1.0",
    "llama-index-vector-stores-chroma>=0.1.0",
    "llama-index-storage-docstore-redis>=0.1.0",
    "llama-index-storage-index-store-redis>=0.1.0",
    "duckdb",
    "neo4j==5.15.0",
    "httpx>=0.26.0",
    "fastapi>=0.109.0",
    "ollama>=0.1.6",
    "pydantic>=2.5.3",
    "torch",
    "types-redis",
    "pytest",
    "aiofiles"
]

[project.scripts]
ramble = "ramble.app:cli"
maxx = "ramblemaxx.app:RambleMaxx.run" 

[tool.hatch.build.targets.wheel]
packages = ["scramble", "ramble", "ramblemaxx"]

[tool.hatch.metadata]
allow-direct-references = true